### ISSUE TITLE
RangeReal values not changed in solver

### ISSUE THREAD

**Issue by lidiamartinez** [Algoryx/AGXUnity#35]
The public variables of Max and Min in ForceRange on a controller are asigned through a RangeReal. but when you change any of them, they are not updated in the solver underneath unless you assign a new RangeReal(x,y) to the ForceRange.

If you provide a "setter" it should be changed in the native object too.
It would not happen if it was a "struct" but since it is a class, it is working differently.

**Comment by nmalg** [comment]
Thanks for reporting this issue. It didn't cross my mind when I implemented it since I only used the Inspector to change the values.

Since there's no connection between the `AGXUnity.RangeReal` and the underlying native object, it's not possible to synchronize the changes. I will change it from class to struct to avoid future mistakes.
